name: ecommerce_analytics
version: "1.0.0"
config-version: 2

profile: ecommerce_analytics

model-paths: ["models"]
macro-paths: ["macros"]

models:
  ecommerce_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: incremental
      +schema: analytics
      +on_schema_change: sync_all_columns

