{{- if or .Values.secrets.awsAccessKeyId .Values.secrets.awsSecretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce-streaming.fullname" . }}-aws
  labels:
    {{- include "ecommerce-streaming.labels" . | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
{{- end }}

