apiVersion: v1
kind: Service
metadata:
  name: {{ include "ecommerce-streaming.fullname" . }}-api
  labels:
    {{- include "ecommerce-streaming.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "ecommerce-streaming.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api

